version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile_backend
    command: bash -c "python manage.py migrate && gunicorn kanban.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - db
    
  db:
    image: postgres:12.4
    environment:
      - POSTGRES_DB=kanban
      - POSTGRES_USER=kanban_user
      - POSTGRES_PASSWORD=kanban_password
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile_frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend

volumes:
  postgres_data:
